### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by gregor-srdic** [apoterenko/angular2-i18next#1]
I tried to install this in my project, but building typescripts returns an error:
TypeScript error: ...MyProject/node_modules/angular2-i18next/src/TranslateI18Next.ts(6,26): Error TS2307: Cannot find module 'bluebird'.
TypeScript error: ...MyProject/node_modules/angular2-i18next/src/TranslateI18Next.ts(11,17): Error TS2304: Cannot find name 'require'.
I have added bluebird dependency to typings.json and also tried to install bluebird via npm, no success.
Any help appriciated

**Comment by apoterenko** [comment]
Hello! Try install node as a global type

"globalDependencies": {
	"node": 
"github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#8cf8164641be73e8f1e652c2a5b967c7210b6729"
 }
``

**Comment by apoterenko** [comment]
Hello!

Which version are you using?

Try update node to v5. My current versions are:

Q:\\angular2-smart-logger>npm --version
3.8.3

Q:\angular2-smart-logger>node --version
v5.10.1

Maybe you should use tsconfig.json as target option for your ts compiler?

**Comment by apoterenko** [comment]
I have removed bluebird dependency
